# Generated by Django 5.0.6 on 2024-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='main_img',
            field=models.ImageField(default='no_image.jpeg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
