# Generated by Django 4.2.13 on 2024-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_reserved_by_listing_reserved_by_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
    ]
