# Generated by Django 4.2.13 on 2024-07-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='available',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='reserved_by_id',
        ),
    ]
