version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Set up Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            python3 -m pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install -r requirements.txt
      - run:
          name: Run tests
          command: python3 manage.py test
workflows:
  build-and-test:
    jobs:
      - test-python