# Generated by Django 5.0.6 on 2024-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_password_request',
            field=models.BooleanField(default=False, help_text='This will allow the the user to perform password reset', verbose_name='User has been granted a password reset'),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_reset_password',
            field=models.BooleanField(default=False, help_text='This will allow the admin to allow a password reset', verbose_name='User has requested a password reset'),
        ),
    ]
