# Generated by Django 5.0.6 on 2024-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date_ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
    ]
