# Generated by Django 4.2.13 on 2024-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_date_ordered_order_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reservation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
